version: '3'

services:
  mysql:
    image: mysql:8.0.25
    container_name: mysql
    environment:
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/1.sql
      - mysqldata:/var/lib/mysql
    networks:
      - backend
    restart: always
  eureka:
    build:
      context: ../rengars_eureka
      dockerfile: Dockerfile
    container_name: eureka
    restart: unless-stopped
    ports:
      - "${EUREKA_PORT}:${EUREKA_PORT}"
    networks:
      - backend
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    expose:
      - ${RABBIT_MQ_PORT}
    ports:
      - "15672:15672"
    networks:
      - backend
    restart: on-failure
  users:
    container_name: users
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: ${USERS_PORT}
      EUREKA_URL: "${EUREKA_HOST}:${EUREKA_PORT}"
      RABBIT_MQ_HOST: ${RABBIT_MQ_HOST}
      RABBIT_MQ_PORT: ${RABBIT_MQ_PORT}
      RABBIT_MQ_EXCHANGE: ${RABBIT_MQ_EXCHANGE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      APP_ENV: ${APP_ENV}
    ports:
      - "${USERS_PORT}:${USERS_PORT}"
    depends_on:
      - mysql
      - eureka
      - rabbitmq
    links:
      - mysql
    volumes:
      - usersdata:/usr/src/users/
    networks:
      - backend
    restart: on-failure

networks:
  backend:
    driver: bridge


volumes:
  mysqldata:
    driver: local
  usersdata:
    driver: local